
station_choices = {
	
	"seke"	:	"Seke",
	"malampaka"	:	"Malampaka",
	"malya"	:	"Malya",
	"bukwimba"	:	"Bukwimba",
	"mantare"	:	"Mantare",
	"fela"	:	"Fela",
	"mwanza south"	:	"Mwanza South",
	"mwanza  town"	:	"Mwanza  Town",
	"tanga"	:	"Tanga",
	"pongwe"	:	"Pongwe",
	"ngomeni"	:	"Ngomeni",
	"muheza"	:	"Muheza",
	"tengeni"	:	"Tengeni",
	"kihuhwi"	:	"Kihuhwi",
	"mruazi junction"	:	"Mruazi Junction",
	"mnyusi"	:	"Mnyusi",
	"korogwe"	:	"Korogwe",
	"ngombezi"	:	"Ngombezi",
	"maurui"	:	"Maurui",
	"makuyuni"	:	"Makuyuni",
	"mombo"	:	"Mombo",
	"mazinde"	:	"Mazinde",
	"mkumbara"	:	"Mkumbara",
	"mkomazi"	:	"Mkomazi",
	"buiko"	:	"Buiko",
	"hedaru"	:	"Hedaru",
	"makanya"	:	"Makanya",
	"same"	:	"Same",
	"lembeni"	:	"Lembeni",
	"kisangiro"	:	"Kisangiro",
	"kahe junction"	:	"Kahe Junction",
	"moshi"	:	"Moshi",
	"kikuletwa"	:	"Kikuletwa",
	"usa river"	:	"Usa River",
	"arusha"	:	"Arusha",
	"mrauzi junction"	:	"Mrauzi Junction",
	"makinyumbi"	:	"Makinyumbi",
	"genda genda"	:	"Genda genda",
	"mkalamo"	:	"Mkalamo",
	"mvave"	:	"Mvave",
	"wami"	:	"Wami",
	"usigwa"	:	"Usigwa",
	"ruvu junction"	:	"Ruvu Junction",
	"manyoni"	:	"Manyoni",
	"mkwese"	:	"Mkwese",
	"isuna"	:	"Isuna",
	"ikungi"	:	"Ikungi",
	"puma"	:	"Puma",
	"singida"	:	"Singida",



}